steps:
  # 1. Construir la imagen del contenedor Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'southamerica-east1-docker.pkg.dev/serenisima-api-desa/biblio-api/biblio-api:$COMMIT_SHA'
      - '.'

  # 2. Subir la imagen a Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'southamerica-east1-docker.pkg.dev/serenisima-api-desa/biblio-api/biblio-api:$COMMIT_SHA'

  # 3. Desplegar el contenedor en Cloud Run
  # --- CAMBIO IMPORTANTE AQUÍ ---
  - name: 'gcr.io/cloud-builders/gcloud' # Usamos el constructor específico de Cloud Build
    args:
      - 'run'
      - 'deploy'
      - 'biblio-api'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/serenisima-api-desa/biblio-api/biblio-api:$COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'southamerica-east1-docker.pkg.dev/serenisima-api-desa/biblio-api/biblio-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY